### ISSUE TITLE
Including an `invalid percentage` check causes Soda Cloud to throw a `400` error

### ISSUE THREAD

**Issue by dirkgroenen** [sodadata/soda-core#1151]
I ran a scan with the following SodaCL file: 

```yaml
checks for CUSTOMERS:

  # And very configurable
  - invalid_percent(pct) < 5 %:
      missing values: ['N/A', 'No value']
      valid format: percentage
      valid length: 4
```

I was expecting it to be submitted to Soda Cloud so I could see the check as a monitor, but an error was returned when Soda Core tried to make the call to Soda Cloud. 

```
 | Stacktrace:
  | Traceback (most recent call last):
  |   File "/home/dirk/work/soda/code/meuk/data-council-workshop/.venv/lib/python3.8/site-packages/soda/scan.py", line 418, in execute
  |     self._configuration.soda_cloud.send_scan_results(self)
  |   File "/home/dirk/work/soda/code/meuk/data-council-workshop/.venv/lib/python3.8/site-packages/soda/soda_cloud/soda_cloud.py", line 28, in send_scan_results
  |     self.cloud_client.insert_scan_results(scan_results)
  |   File "/home/dirk/work/soda/code/meuk/data-council-workshop/.venv/lib/python3.8/site-packages/soda/soda_cloud/soda_cloud_client.py", line 28, in insert_scan_results
  |     return self._execute_command(scan_results)
  |   File "/home/dirk/work/soda/code/meuk/data-council-workshop/.venv/lib/python3.8/site-packages/soda/soda_cloud/soda_cloud_client.py", line 32, in _execute_command
  |     return self._execute_request("command", command, False)
  |   File "/home/dirk/work/soda/code/meuk/data-council-workshop/.venv/lib/python3.8/site-packages/soda/soda_cloud/soda_cloud_client.py", line 44, in _execute_request
  |     assert (
  | AssertionError: Request failed with status 400: {
  |   "code": "invalid_request",
  |   "message": "Could not parse command from json body: {\"definitionName\": \"dirks_local_test\", \"dataTimestamp\": \"2022-03-22T16:33:46.669708\", \"scanStartTimestamp\": \"2022-03-22T16:33:46.669708\", \"scanEndTimestamp\": \"2022-03-22T17:33:46.735127\", \"hasErrors\": false, \"hasWarnings\": false, \"hasFailures\": true, \"metrics\": [{\"identity\": \"metric-dirks_local_test-workshop_ds-CUSTOMERS-pct-invalid_percent-c1fe7584\", \"metricName\": \"invalid_percent\", \"value\": 70.0}, {\"identity\": \"metric-dirks_local_test-workshop_ds-CUSTOMERS-pct-invalid_count-c1fe7584\", \"metricName\": \"invalid_count\", \"value\": 7}, {\"identity\": \"metric-dirks_local_test-workshop_ds-CUSTOMERS-row_count\", \"metricName\": \"row_count\", \"value\": 10}], \"checks\": [{\"identity\": \"check-dirks_local_test-workshop_ds-CUSTOMERS-pct-invalid_percent-af1e9ef6\", \"name\": \"invalid_percent(pct) < 5 %\", \"type\": \"metricThreshold\", \"definition\": \"checks for CUSTOMERS:\\n  - invalid_percent(pct) < 5 %:\\n      missing values: ['N/A', 'No value']\\n      valid format: percentage\\n      valid length: 4\\n\\n#       # missing regex: \\\\ *\\n#       # valid regex: .*\\n#       # valid min: 0\\n#       # valid max: 100\\n#       # valid min length: 3\\n#       # valid max length: 5\\n#       # valid length: 16\\n\\n#   # generating an error will:\\n#   #  - still execute the scan as much as possible\\n#   #  - produce detailed error report to enable self serve\\n\", \"location\": {\"filePath\": \"checks/01_basic_checks.yml\", \"line\": 15, \"col\": 5}, \"dataSource\": \"workshop_ds\", \"table\": \"CUSTOMERS\", \"column\": \"pct\", \"metrics\": [\"metric-dirks_local_test-workshop_ds-CUSTOMERS-pct-invalid_percent-c1fe7584\"], \"outcome\": \"fail\", \"diagnostics\": {\"value\": 70.0, \"formula_values\": {\"row_count\": 10, \"invalid_count\": 7}, \"fail\": {\"greaterThanOrEqual\": 5.0}}}], \"type\": \"sodaCoreInsertScanResults\", \"token\":\"***hidden***\"}"
  | }

```

I was looking at the send JSON, but I can't spot an issue right away. Perhaps @milanaleksic or @Antoninj can spot if something is missing or not? 

```jsonc
{
	"definitionName": "dirks_local_test",
	"dataTimestamp": "2022-03-22T16:33:46.669708",
	"scanStartTimestamp": "2022-03-22T16:33:46.669708",
	"scanEndTimestamp": "2022-03-22T17:33:46.735127",
	"hasErrors": false,
	"hasWarnings": false,
	"hasFailures": true,
	"metrics": [{
			"identity": "metric-dirks_local_test-workshop_ds-CUSTOMERS-pct-invalid_percent-c1fe7584",
			"metricName": "invalid_percent",
			"value": 70.0
		},
		{
			"identity": "metric-dirks_local_test-workshop_ds-CUSTOMERS-pct-invalid_count-c1fe7584",
			"metricName": "invalid_count",
			"value": 7
		},
		{
			"identity": "metric-dirks_local_test-workshop_ds-CUSTOMERS-row_count",
			"metricName": "row_count",
			"value": 10
		}
	],
	"checks": [{
		"identity": "check-dirks_local_test-workshop_ds-CUSTOMERS-pct-invalid_percent-af1e9ef6",
		"name": "invalid_percent(pct) < 5 %",
		"type": "metricThreshold",
		"definition": "checks for CUSTOMERS:\n  - invalid_percent(pct) < 5 %:\n      missing values: ['N/A', 'No value']\n      valid format: percentage\n      valid length: 4\n\n#       # missing regex: \\ *\n#       # valid regex: .*\n#       # valid min: 0\n#       # valid max: 100\n#       # valid min length: 3\n#       # valid max length: 5\n#       # valid length: 16\n\n#   # generating an error will:\n#   #  - still execute the scan as much as possible\n#   #  - produce detailed error report to enable self serve\n",
		"location": {
			"filePath": "checks/01_basic_checks.yml",
			"line": 15,
			"col": 5
		},
		"dataSource": "workshop_ds",
		"table": "CUSTOMERS",
		"column": "pct",
		"metrics": [
			"metric-dirks_local_test-workshop_ds-CUSTOMERS-pct-invalid_percent-c1fe7584"
		],
		"outcome": "fail",
		"diagnostics": {
			"value": 70.0,
			"formula_values": {
				"row_count": 10,
				"invalid_count": 7
			},
			"fail": {
				"greaterThanOrEqual": 5.0
			}
		}
	}],
	"type": "sodaCoreInsertScanResults"
}
```

**Comment by vijaykiran** [comment]
My guess is `formula_values.row_count|invalid_count` is triggering this error. I'll check it.

**Comment by milanaleksic** [comment]
yes, it's `formula_values`, it breaks the parser. It shouldn't though since it's an add-on, but try not to send it for now until JSON parser can be fixed to handle it
