### ISSUE TITLE
Improve error message - Schema checks

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1191]
This check works as expected:
```yaml
checks for sodatest_customers_b7580920:
 - schema:
   warn:
    when required column missing: [sombrero]
```
```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Scan summary:
1/1 check WARNED: 
  sodatest_customers_b7580920 in local_postgres_sodasql
   schema [WARNED]
    missing_column_names = [sombrero]
    schema_measured = [id character varying, size double precision, sizetxt character varying, distance integer, pct character varying, cat character varying, country character varying, zip character varying, email character varying, date date, ts timestamp without time zone, ts_with_tz timestamp with time zone]
Only 1 warning. 0 failure. 0 errors. 0 pass.
```

But when I purposely messed up my syntax by adding an errant `when`, the error message is misleading in pointing out what exactly is wrong. The colon in line 5 isn’t the problem, the aimless extra when is the issue. More precise error message?
```yaml
checks for sodatest_customers_b7580920:
 - schema:
   warn:
    when
    when required column missing: [sombrero]
```
```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
YAML syntax error
 | mapping values are not allowed here
 |  in "<unicode string>", line 5, column 37:
 |       when required column missing: [sombrero]
 |                     ^ (line: 5)
 | Stacktrace:
 | Traceback (most recent call last):
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/common/parser.py", line 65, in _parse_yaml_str
 |   file_dict = yaml.load(yaml_str)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/main.py", line 434, in load
 |   return constructor.get_single_data()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
 |   node = self.composer.get_single_node()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
 |   document = self.compose_document()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
 |   node = self.compose_node(None, None)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
 |   node = self.compose_mapping_node(anchor)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
 |   item_value = self.compose_node(node, item_key)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 141, in compose_node
 |   node = self.compose_sequence_node(anchor)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 185, in compose_sequence_node
 |   node.value.append(self.compose_node(node, index))
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
 |   node = self.compose_mapping_node(anchor)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
 |   item_value = self.compose_node(node, item_key)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
 |   node = self.compose_mapping_node(anchor)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
 |   item_value = self.compose_node(node, item_key)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 113, in compose_node
 |   if self.parser.check_event(AliasEvent):
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 146, in check_event
 |   self.current_event = self.state()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 629, in parse_block_mapping_value
 |   if self.scanner.check_token(ValueToken):
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 1796, in check_token
 |   self._gather_comments()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 1838, in _gather_comments
 |   self.fetch_more_tokens()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 288, in fetch_more_tokens
 |   return self.fetch_value()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 657, in fetch_value
 |   raise ScannerError(
 | ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
 |  in "<unicode string>", line 5, column 37:
 |       when required column missing: [sombrero]
 |                     ^ (line: 5)

 +-> line=5,col=37 in checks.yaml
Scan summary:
1 errors.
Oops! 1 error. 0 failures. 0 warnings. 0 pass.
ERRORS:
YAML syntax error
 | mapping values are not allowed here
 |  in "<unicode string>", line 5, column 37:
 |       when required column missing: [sombrero]
 |                     ^ (line: 5)
 | Stacktrace:
 | Traceback (most recent call last):
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/common/parser.py", line 65, in _parse_yaml_str
 |   file_dict = yaml.load(yaml_str)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/main.py", line 434, in load
 |   return constructor.get_single_data()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
 |   node = self.composer.get_single_node()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
 |   document = self.compose_document()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
 |   node = self.compose_node(None, None)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
 |   node = self.compose_mapping_node(anchor)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
 |   item_value = self.compose_node(node, item_key)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 141, in compose_node
 |   node = self.compose_sequence_node(anchor)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 185, in compose_sequence_node
 |   node.value.append(self.compose_node(node, index))
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
 |   node = self.compose_mapping_node(anchor)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
 |   item_value = self.compose_node(node, item_key)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
 |   node = self.compose_mapping_node(anchor)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
 |   item_value = self.compose_node(node, item_key)
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 113, in compose_node
 |   if self.parser.check_event(AliasEvent):
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 146, in check_event
 |   self.current_event = self.state()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 629, in parse_block_mapping_value
 |   if self.scanner.check_token(ValueToken):
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 1796, in check_token
 |   self._gather_comments()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 1838, in _gather_comments
 |   self.fetch_more_tokens()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 288, in fetch_more_tokens
 |   return self.fetch_value()
 |  File "/Users/Janet/Documents/GitHub/soda-sql-v3/.venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 657, in fetch_value
 |   raise ScannerError(
 | ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
 |  in "<unicode string>", line 5, column 37:
 |       when required column missing: [sombrero]
 |                     ^ (line: 5)

 +-> line=5,col=37 in checks.yaml
```

**Comment by tombaeyens** [comment]
@vijaykiran closing this as it's a minor compared to all the work we still have ahead.  If you want to keep this, then I suggest you create a skipped unit test that produces this error and create a ticket on the backlog referring to that unit test.  The logs and error handling will change anyways.  So we ll have to see after that refactoring if this still produces a bad error messsage
