### ISSUE TITLE
Improve error message missing column - Statistical

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1194]
For this check, I left out the column name to see what would happen and it errored as expected but maybe the error message could be improved? 
`'NoneType' object has no attribute 'column_name' `+ a stacktrace is... not super useful. Could it be shortened to just "Missing column name"? 

(Also, need to correct the docs for the metric: should be 'stddev' instead of 'stdev'.)

```yaml
checks for sodatest_customers_b7580920:
  - stdev > 4
```

```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Unknown error while executing scan.
  | 'NoneType' object has no attribute 'column_name'
  | Stacktrace:
  | Traceback (most recent call last):
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/scan.py", line 323, in execute
  |     self.__create_check(check_cfg, data_source_scan, partition)
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/scan.py", line 470, in __create_check
  |     check = Check.create(
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/check.py", line 37, in create
  |     return MetricCheck(check_cfg, data_source_scan, partition, column)
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/metric_check.py", line 79, in __init__
  |     metric = data_source_scan.resolve_metric(metric)
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/data_source_scan.py", line 46, in resolve_metric
  |     metric.ensure_query()
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/numeric_query_metric.py", line 126, in ensure_query
  |     self.partition.ensure_query_for_metric(self)
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/partition.py", line 56, in ensure_query_for_metric
  |     sql_aggregation_expression = metric.get_sql_aggregation_expression()
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/numeric_query_metric.py", line 92, in get_sql_aggregation_expression
  |     values_expression = self.column.column_name
  | AttributeError: 'NoneType' object has no attribute 'column_name'
```

**Comment by tombaeyens** [comment]
Merged into #1234
