### ISSUE TITLE
Attribute error due to a parsing issue with a typo

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1199]
@tombaeyens you asked me to file an issue with the situation I had a full on traceback

my check was written like so with an intentional typo to see what the parser says:
```yaml
checks for new_fact_currency_rate:
  - countsame as fact_currency_rate
```

This gave:
```
root@0c07d91bb019:/sodacl# soda scan -d adventureworks -c configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Invalid check "countsame as fact_currency_rate": mismatched input 'as' expecting {'between', 'not', 'warn', 'fail', 'pass', '!=', '<>', '<=', '>=', '=', '<', '>'}
  +-> line=9,col=5 in checks.yaml
  +-> See https://go.soda.io/SECTHEADER
No threshold specified for check "countsame as fact_currency_rate"
  +-> line=9,col=5 in checks.yaml
Unknown error while executing scan.
  | 'NoneType' object has no attribute 'column_name'
  | Stacktrace:
  | Traceback (most recent call last):
  |   File "/usr/local/lib/python3.8/dist-packages/soda_core/scan.py", line 327, in execute
  |     self.__create_check(check_cfg, data_source_scan, partition)
  |   File "/usr/local/lib/python3.8/dist-packages/soda_core/scan.py", line 480, in __create_check
  |     check.ensure_metrics_and_queries(data_source_scan=data_source_scan, partition=partition)
  |   File "/usr/local/lib/python3.8/dist-packages/soda_core/execution/metric_check.py", line 84, in ensure_metrics_and_queries
  |     metric = data_source_scan.resolve_metric(metric)
  |   File "/usr/local/lib/python3.8/dist-packages/soda_core/execution/data_source_scan.py", line 46, in resolve_metric
  |     metric.ensure_query()
  |   File "/usr/local/lib/python3.8/dist-packages/soda_core/execution/numeric_query_metric.py", line 183, in ensure_query
  |     self.partition.ensure_query_for_metric(self)
  |   File "/usr/local/lib/python3.8/dist-packages/soda_core/execution/partition.py", line 58, in ensure_query_for_metric
  |     sql_aggregation_expression = metric.get_sql_aggregation_expression()
  |   File "/usr/local/lib/python3.8/dist-packages/soda_core/execution/numeric_query_metric.py", line 149, in get_sql_aggregation_expression
  |     values_expression = self.column.column_name
  | AttributeError: 'NoneType' object has no attribute 'column_name'
```

**Comment by tombaeyens** [comment]
Replaced by #1234
