### ISSUE TITLE
Re-implement SodaCL parser

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1234]
Goals:
* Improving the error messages
* Check type pluggability
* Reduce complexity in the parser
* Introduce a new typed AST that directly resembles the files and language structures as an intermediate before merging the things together.

**Comment by tombaeyens** [comment]
Merged here from #1211  :

```
Invalid check "columns types": no viable alternative at input 'columnstypes'
  +-> checks.yml line=4,col=5 "checks for actor"."[1]"(columns types)
Couldn't detect table check type of 'columns types'
  +-> checks.yml line=4,col=5 "checks for actor"."[1]"(columns types)
INFO   | Reading SodaCL file "environments.yml"
INFO   | Reading SodaCL file "checks.yml"
ERROR  | Invalid check "columns types": no viable alternative at input 'columnstypes' checks.yml line=4,col=5 "checks for actor"."[1]"(columns types)
ERROR  | Couldn't detect table check type of 'columns types' checks.yml line=4,col=5 "checks for actor"."[1]"(columns types)
```

- In the error "columnstypes" without spaces shows up
- The error is caught in 2 places ?

**Comment by tombaeyens** [comment]
Merged here from #1194 :

For this check, I left out the column name to see what would happen and it errored as expected but maybe the error message could be improved? 
`'NoneType' object has no attribute 'column_name' `+ a stacktrace is... not super useful. Could it be shortened to just "Missing column name"? 

(Also, need to correct the docs for the metric: should be 'stddev' instead of 'stdev'.)

```yaml
checks for sodatest_customers_b7580920:
  - stdev > 4
```

```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Unknown error while executing scan.
  | 'NoneType' object has no attribute 'column_name'
  | Stacktrace:
  | Traceback (most recent call last):
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/scan.py", line 323, in execute
  |     self.__create_check(check_cfg, data_source_scan, partition)
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/scan.py", line 470, in __create_check
  |     check = Check.create(
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/check.py", line 37, in create
  |     return MetricCheck(check_cfg, data_source_scan, partition, column)
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/metric_check.py", line 79, in __init__
  |     metric = data_source_scan.resolve_metric(metric)
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/data_source_scan.py", line 46, in resolve_metric
  |     metric.ensure_query()
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/numeric_query_metric.py", line 126, in ensure_query
  |     self.partition.ensure_query_for_metric(self)
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/partition.py", line 56, in ensure_query_for_metric
  |     sql_aggregation_expression = metric.get_sql_aggregation_expression()
  |   File "/Users/Janet/Documents/GitHub/soda-sql-v3/soda_core/soda_core/execution/numeric_query_metric.py", line 92, in get_sql_aggregation_expression
  |     values_expression = self.column.column_name
  | AttributeError: 'NoneType' object has no attribute 'column_name'
```

**Comment by tombaeyens** [comment]
Merged here from #1190 

A couple of unexpected things with this check. I copy+pasted this out of the docs, changing only the column name and adding the extra check for `count > 0`.
```yaml
checks for sodatest_customers_b7580920:
 - count > 0
 - invalid_percent(country) < 1%:
   missing values: [N/A, No value, null]
```

And the output confused me.

- First, because it advised that `Only strings or only numbers allowed in missing values: [‘N/A’, ‘No value’, None]`
- and secondly, because it executed the check anyway and found that it passed! 

Of course, it has no correct missing values to check against, but I would expect that if the missing values errors out, the check that uses the missing values would also error out, or at least not pass.

```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Only strings or only numbers allowed in missing values: ['N/A', 'No value', None]
 +-> line=4,col=7 in checks.yaml
Counting invalid without valid specification does not make sense
Scan summary:
2/2 checks PASSED: 
  sodatest_customers_b7580920 in local_postgres_sodasql
   count > 0 [PASSED]
   invalid_percent(country) < 1% [PASSED]
1 errors.
Oops! 1 error. 0 failures. 0 warnings. 2 pass.
ERRORS:
Only strings or only numbers allowed in missing values: ['N/A', 'No value', None]
 +-> line=4,col=7 in checks.yaml
```

This one worked, though, without the square brackets. Though now it occurs to me that the square brackets are perhaps not needed in the check, but were in the docs to communicate "these are your options for the value to put here".
```yaml
checks for sodatest_customers_b7580920:
 - count > 0
 - invalid_percent(country) < 1%:
   missing values: N/A
```
```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Counting invalid without valid specification does not make sense
Scan summary:
2/2 checks PASSED: 
  sodatest_customers_b7580920 in local_postgres_sodasql
   count > 0 [PASSED]
   invalid_percent(country) < 1% [PASSED]
All is good. No failures. No warnings. No errors.
```

And this did not work as expected. Though I was hoping the error message might tell me what I think I have already deduced, that you can only use a string for missing values, not a list.
```yaml
checks for sodatest_customers_b7580920:
 - count > 0
 - invalid_percent(country) < 1%:
   missing values: N/A, None
```
```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Counting invalid without valid specification does not make sense
Scan summary:
2/2 checks PASSED: 
  sodatest_customers_b7580920 in local_postgres_sodasql
   count > 0 [PASSED]
   invalid_percent(country) < 1% [PASSED]
All is good. No failures. No warnings. No errors.
```

**Comment by tombaeyens** [comment]
Merged from #1185 

Trying to use a warn in a check that uses a statistical metric and it SKIPPED the check. 
```yaml
checks for sodatest_customers_b7580920:
  warn:
    when min(size) >= 0
```
```
Soda Core 0.0.1
Skipping section "checks for sodatest_customers_b7580920" because content is not a list
  +-> line=1,col=1 in checks.yaml
Scan summary:
1 errors.
Oops! 1 error. 0 failures. 0 warnings. 0 pass.
ERRORS:
Skipping section "checks for sodatest_customers_b7580920" because content is not a list
  +-> line=1,col=1 in checks.yaml
```

I tried this one as well:
```yaml
checks for sodatest_customers_b7580920:
  warn:
    - when stddev(size) between 3 and 4
```

```
Soda Core 0.0.1
Skipping section "checks for sodatest_customers_b7580920" because content is not a list
  +-> line=1,col=1 in checks.yaml
Scan summary:
1 errors.
Oops! 1 error. 0 failures. 0 warnings. 0 pass.
ERRORS:
Skipping section "checks for sodatest_customers_b7580920" because content is not a list
  +-> line=1,col=1 in checks.yaml
```


Same error appears when I attempt to use `warn` with a freshness check:
```yaml
checks for sodatest_customers_b7580920:
  warn:
    when freshness using last_name < 1h
```
