### ISSUE TITLE
ZeroDivisionError for `*_percentage` checks should result in zero

### ISSUE THREAD

**Issue by jasonicarter** [sodadata/soda-core#1311]
For percentage calculations, if you have zero rows you should just return a zero result. My thinking is...

1. The `ZeroDivisionError` shouldn't error out causing the entire scan to fail
2. If there are zero rows then there is no missing_percentage and therefore the answer should be zero `missing_percentage = 0`

```
Error occurred while executing scan.
  | division by zero
  | Stacktrace:
  | Traceback (most recent call last):
  |   File "/usr/local/lib/python3.9/site-packages/soda/scan.py", line 314, in execute
  |     metric.compute_derived_metric_values()
  |   File "/usr/local/lib/python3.9/site-packages/soda/execution/derived_metric.py", line 123, in compute_derived_metric_values
  |     self.value = self.derived_formula.function(formula_values)
  |   File "/usr/local/lib/python3.9/site-packages/soda/execution/derived_metric.py", line 62, in derive_missing_percentage
  |     missing_percentage = values["missing_count"] * 100 / values["row_count"]
  | ZeroDivisionError: division by zero
  ```

**Comment by jmarien** [comment]
SODA-212
