### ISSUE TITLE
Dependency issue with 3.0.9

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1609]
When running soda 3.0.9 scan  I run into the following exception:
`
(soda-core-3.0.9) $soda scan -d aws_postgres_retail sales.yml
Traceback (most recent call last):
 File "/Users/albin/dev/py/env/soda-core-3.0.9/bin/soda", line 5, in <module>
  from soda.cli.cli import main
 File "/Users/albin/dev/py/env/soda-core-3.0.9/lib/python3.10/site-packages/soda/cli/cli.py", line 24, in <module>
  from soda.scan import Scan
 File "/Users/albin/dev/py/env/soda-core-3.0.9/lib/python3.10/site-packages/soda/scan.py", line 28, in <module>
  from soda.telemetry.soda_telemetry import SodaTelemetry
 File "/Users/albin/dev/py/env/soda-core-3.0.9/lib/python3.10/site-packages/soda/telemetry/soda_telemetry.py", line 17, in <module>
  from soda.telemetry.soda_exporter import SodaConsoleSpanExporter, SodaOTLPSpanExporter
 File "/Users/albin/dev/py/env/soda-core-3.0.9/lib/python3.10/site-packages/soda/telemetry/soda_exporter.py", line 5, in <module>
  from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
 File "/Users/albin/dev/py/env/soda-core-3.0.9/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 40, in <module>
  from opentelemetry.exporter.otlp.proto.http.trace_exporter.encoder import (
 File "/Users/albin/dev/py/env/soda-core-3.0.9/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/encoder/__init__.py", line 19, in <module>
  from opentelemetry.proto.collector.trace.v1.trace_service_pb2 import (
 File "/Users/albin/dev/py/env/soda-core-3.0.9/lib/python3.10/site-packages/opentelemetry/proto/collector/trace/v1/trace_service_pb2.py", line 5, in <module>
  from google.protobuf import descriptor as _descriptor
 File "/Users/albin/dev/py/env/soda-core-3.0.9/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 47, in <module>
  from google.protobuf.pyext import _message
ImportError: dlopen(/Users/albin/dev/py/env/soda-core-3.0.9/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (__ZN6google8protobuf15FieldDescriptor12TypeOnceInitEPKS1_)
`

**Comment by albinkjellin** [comment]
This can be resolved by downgrade protobuf:
pip uninstall protobuf
pip install protobuf==3.19.4

**Comment by jmarien** [comment]
SODA-1195

**Comment by vijaykiran** [comment]
https://github.com/protocolbuffers/protobuf/issues/10571

**Comment by vijaykiran** [comment]
This is an upstream issue - closing this because the upstream bug seems to be fixed.
