### ISSUE TITLE
OverflowError: cannot convert float infinity to integer in Soda Core 3.0.10

### ISSUE THREAD

**Issue by mrafayaleem** [sodadata/soda-core#1621]
Just updated the library to `3.0.10` and getting the following error which seems to be in relation to this [pull request](https://github.com/sodadata/soda-core/pull/1616)

Library is also generating a dive by zero warning. See the stacktrace below.

```
Soda Core 3.0.10
/opt/anaconda3/envs/faire-airflow/lib/python3.9/site-packages/soda/scientific/distribution/generate_dro.py:35: RuntimeWarning: divide by zero encountered in double_scalars
  n_bins = int(np.ceil(np.lib.histograms._unsigned_subtract(last_edge, first_edge) / bin_width))
Traceback (most recent call last):
  File "/Users/aleem/Development/datascience/apps/data_monitoring/soda_framework.py", line 340, in <module>
    run_data_checks()
  File "/opt/anaconda3/envs/faire-airflow/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/faire-airflow/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/faire-airflow/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/faire-airflow/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/aleem/Development/datascience/apps/data_monitoring/soda_framework.py", line 334, in run_data_checks
    framework.update_dro(dro_references, namespace, entity_name)
  File "/Users/aleem/Development/datascience/apps/data_monitoring/soda_framework.py", line 165, in update_dro
    self.build_dro_locally(file_paths, verbose)
  File "/Users/aleem/Development/datascience/apps/data_monitoring/soda_framework.py", line 243, in build_dro_locally
    update_dro_func(
  File "/opt/anaconda3/envs/faire-airflow/lib/python3.9/site-packages/soda/cli/cli.py", line 346, in update_dro
    dro = DROGenerator(RefDataCfg(distribution_type=distribution_type), column_values).generate()
  File "/opt/anaconda3/envs/faire-airflow/lib/python3.9/site-packages/soda/scientific/distribution/generate_dro.py", line 121, in generate
    return self.generate_continuous_dro()
  File "/opt/anaconda3/envs/faire-airflow/lib/python3.9/site-packages/soda/scientific/distribution/generate_dro.py", line 70, in generate_continuous_dro
    n_bins = self._compute_n_bins(data)
  File "/opt/anaconda3/envs/faire-airflow/lib/python3.9/site-packages/soda/scientific/distribution/generate_dro.py", line 35, in _compute_n_bins
    n_bins = int(np.ceil(np.lib.histograms._unsigned_subtract(last_edge, first_edge) / bin_width))
OverflowError: cannot convert float infinity to integer
```

**Comment by jmarien** [comment]
SODA-1204

**Comment by mrafayaleem** [comment]
Query like the following generated this error in Snowflake
```sql
SELECT <column> FROM <table> sample row (50000 rows) WHERE ds <= '2022-08-31' and ds >= '2022-06-01' and <column> is not null
```
