### ISSUE TITLE
Issues with BQ 3.0.10

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1637]
I have the following config:

```yaml
checks for datalake_awe_reporting_form_submit:
  - invalid_count(city) = 0:
      valid regex: ^[a-zA-Z0-9_@./#&+-áåäö]*$
      name: Validity alpha numeric and special characters
  - invalid_count(vertical) = 0:
      valid values:
          - AUTOMOBILE.LEASEBUYOUT
          - AUTOMOBILE.PURCHASE
          - AUTOMOBILE.REFINANCE
          - BUSINESSLOAN
          - HOMEEQUITY
          - INVESTMENT
          - MORTGAGE.PURCHASE
          - MORTGAGE.REFINANCE
          - PERSONAL
          - REVERSEMORTGAGE
      name: Validate vertical values
```

That works well in 3.0.9 but with 3.0.10 it hangs and when I shut it down it gives the following error:

```
(soda-core-3.0.10-2) $soda scan -d bq issue.yml -V
Soda Core 3.0.10
Reading configuration file "/Users/albin/.soda/configuration.yml"
Reading SodaCL file "issue.yml"
Scan execution starts
/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/client.py:535: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(
Query bq.datalake_awe_reporting_form_submit.aggregation[0]:
SELECT 
  COUNT(CASE WHEN NOT (city IS NULL) AND NOT (REGEXP_CONTAINS(city, r'^[a-zA-Z0-9_@./#&+-áåäö]*$')) THEN 1 END),
  COUNT(CASE WHEN NOT (vertical IS NULL) AND NOT (vertical IN ('AUTOMOBILE.LEASEBUYOUT','AUTOMOBILE.PURCHASE','AUTOMOBILE.REFINANCE','BUSINESSLOAN','HOMEEQUITY','INVESTMENT','MORTGAGE.PURCHASE','MORTGAGE.REFINANCE','PERSONAL','REVERSEMORTGAGE')) THEN 1 END) 
FROM lt.datalake_awe_reporting_form_submit
This service is instrumented using OpenTelemetry. OpenTelemetry or one of its components could not be imported; please add compatible versions of opentelemetry-api and opentelemetry-instrumentation packages in order to get BigQuery Tracing data.
Making request: POST https://oauth2.googleapis.com/token
Query bq.city.failed_rows[invalid_count]:
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT city IS NULL AND NOT REGEXP_CONTAINS(city, r'^[a-zA-Z0-9_@./#&+-áåäö]*$')
^CQuery error: bq.city.failed_rows[invalid_count]: 
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT city IS NULL AND NOT REGEXP_CONTAINS(city, r'^[a-zA-Z0-9_@./#&+-áåäö]*$')

  | Stacktrace:
  | Traceback (most recent call last):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/execution/query/query.py", line 181, in store
  |     self.sample_ref = sampler.store_sample(sample_context)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/sampler/soda_cloud_sampler.py", line 10, in store_sample
  |     sample_rows = sample_context.sample.get_rows()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/sampler/db_sample.py", line 13, in get_rows
  |     return self.cursor.fetchall()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
  |     return method(self, *args, **kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 383, in fetchall
  |     return list(self._query_data)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 208, in _items_iter
  |     for page in self._page_iter(increment=False):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 250, in _page_iter
  |     page = self._next_page()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 373, in _next_page
  |     response = self._get_next_page_response()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/table.py", line 1589, in _get_next_page_response
  |     return self.api_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 784, in _call_api
  |     return call()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
  |     return retry_target(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
  |     return target()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 482, in api_request
  |     response = self._make_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 341, in _make_request
  |     return self._do_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 379, in _do_request
  |     return self.http.request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/auth/transport/requests.py", line 549, in request
  |     response = super(AuthorizedSession, self).request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
  |     resp = self.send(prep, **send_kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
  |     r = adapter.send(request, **kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
  |     resp = conn.urlopen(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
  |     httplib_response = self._make_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
  |     six.raise_from(e, None)
  |   File "<string>", line 3, in raise_from
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
  |     httplib_response = conn.getresponse()
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
  |     response.begin()
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
  |     version, status, reason = self._read_status()
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 279, in _read_status
  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 705, in readinto
  |     return self._sock.recv_into(b)
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1274, in recv_into
  |     return self.read(nbytes, buffer)
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1130, in read
  |     return self._sslobj.read(len, buffer)
  | KeyboardInterrupt

Query bq.vertical.failed_rows[invalid_count]:
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT vertical IS NULL AND NOT vertical IN ('AUTOMOBILE.LEASEBUYOUT','AUTOMOBILE.PURCHASE','AUTOMOBILE.REFINANCE','BUSINESSLOAN','HOMEEQUITY','INVESTMENT','MORTGAGE.PURCHASE','MORTGAGE.REFINANCE','PERSONAL','REVERSEMORTGAGE')
^CQuery error: bq.vertical.failed_rows[invalid_count]: 
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT vertical IS NULL AND NOT vertical IN ('AUTOMOBILE.LEASEBUYOUT','AUTOMOBILE.PURCHASE','AUTOMOBILE.REFINANCE','BUSINESSLOAN','HOMEEQUITY','INVESTMENT','MORTGAGE.PURCHASE','MORTGAGE.REFINANCE','PERSONAL','REVERSEMORTGAGE')

  | Stacktrace:
  | Traceback (most recent call last):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/execution/query/query.py", line 181, in store
  |     self.sample_ref = sampler.store_sample(sample_context)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/sampler/soda_cloud_sampler.py", line 10, in store_sample
  |     sample_rows = sample_context.sample.get_rows()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/sampler/db_sample.py", line 13, in get_rows
  |     return self.cursor.fetchall()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
  |     return method(self, *args, **kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 383, in fetchall
  |     return list(self._query_data)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 208, in _items_iter
  |     for page in self._page_iter(increment=False):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 250, in _page_iter
  |     page = self._next_page()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 373, in _next_page
  |     response = self._get_next_page_response()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/table.py", line 1589, in _get_next_page_response
  |     return self.api_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 784, in _call_api
  |     return call()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
  |     return retry_target(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
  |     return target()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 482, in api_request
  |     response = self._make_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 341, in _make_request
  |     return self._do_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 379, in _do_request
  |     return self.http.request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/auth/transport/requests.py", line 549, in request
  |     response = super(AuthorizedSession, self).request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
  |     resp = self.send(prep, **send_kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/sessions.py", line 687, in send
  |     r.content
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/models.py", line 838, in content
  |     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/models.py", line 760, in generate
  |     for chunk in self.raw.stream(chunk_size, decode_content=True):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/response.py", line 623, in stream
  |     for line in self.read_chunked(amt, decode_content=decode_content):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/response.py", line 815, in read_chunked
  |     self._update_chunk_length()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/response.py", line 745, in _update_chunk_length
  |     line = self._fp.fp.readline()
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 705, in readinto
  |     return self._sock.recv_into(b)
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1274, in recv_into
  |     return self.read(nbytes, buffer)
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1130, in read
  |     return self._sslobj.read(len, buffer)
  | KeyboardInterrupt

Scan summary:
1/3 queries OK
  bq.datalake_awe_reporting_form_submit.aggregation[0] [OK] 0:00:01.464289
  bq.city.failed_rows[invalid_count] [OK] 0:03:48.521796
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT city IS NULL AND NOT REGEXP_CONTAINS(city, r'^[a-zA-Z0-9_@./#&+-áåäö]*$')

  bq.vertical.failed_rows[invalid_count] [OK] 0:00:08.462694
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT vertical IS NULL AND NOT vertical IN ('AUTOMOBILE.LEASEBUYOUT','AUTOMOBILE.PURCHASE','AUTOMOBILE.REFINANCE','BUSINESSLOAN','HOMEEQUITY','INVESTMENT','MORTGAGE.PURCHASE','MORTGAGE.REFINANCE','PERSONAL','REVERSEMORTGAGE')

2/3 queries ERROR
  bq.datalake_awe_reporting_form_submit.aggregation[0] [ERROR] 0:00:01.464289
  bq.city.failed_rows[invalid_count] [ERROR] 0:03:48.521796
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT city IS NULL AND NOT REGEXP_CONTAINS(city, r'^[a-zA-Z0-9_@./#&+-áåäö]*$')

  bq.vertical.failed_rows[invalid_count] [ERROR] 0:00:08.462694
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT vertical IS NULL AND NOT vertical IN ('AUTOMOBILE.LEASEBUYOUT','AUTOMOBILE.PURCHASE','AUTOMOBILE.REFINANCE','BUSINESSLOAN','HOMEEQUITY','INVESTMENT','MORTGAGE.PURCHASE','MORTGAGE.REFINANCE','PERSONAL','REVERSEMORTGAGE')

2/2 checks FAILED: 
    datalake_awe_reporting_form_submit in bq
      Validity alpha numeric and special characters [FAILED]
        check_value: 88999
      Validate vertical values [FAILED]
        check_value: 40264
2 errors.
Oops! 2 errors. 2 failures. 0 warnings. 0 pass.
ERRORS:
Query error: bq.city.failed_rows[invalid_count]: 
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT city IS NULL AND NOT REGEXP_CONTAINS(city, r'^[a-zA-Z0-9_@./#&+-áåäö]*$')

  | Stacktrace:
  | Traceback (most recent call last):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/execution/query/query.py", line 181, in store
  |     self.sample_ref = sampler.store_sample(sample_context)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/sampler/soda_cloud_sampler.py", line 10, in store_sample
  |     sample_rows = sample_context.sample.get_rows()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/sampler/db_sample.py", line 13, in get_rows
  |     return self.cursor.fetchall()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
  |     return method(self, *args, **kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 383, in fetchall
  |     return list(self._query_data)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 208, in _items_iter
  |     for page in self._page_iter(increment=False):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 250, in _page_iter
  |     page = self._next_page()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 373, in _next_page
  |     response = self._get_next_page_response()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/table.py", line 1589, in _get_next_page_response
  |     return self.api_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 784, in _call_api
  |     return call()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
  |     return retry_target(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
  |     return target()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 482, in api_request
  |     response = self._make_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 341, in _make_request
  |     return self._do_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 379, in _do_request
  |     return self.http.request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/auth/transport/requests.py", line 549, in request
  |     response = super(AuthorizedSession, self).request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
  |     resp = self.send(prep, **send_kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
  |     r = adapter.send(request, **kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
  |     resp = conn.urlopen(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
  |     httplib_response = self._make_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
  |     six.raise_from(e, None)
  |   File "<string>", line 3, in raise_from
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
  |     httplib_response = conn.getresponse()
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
  |     response.begin()
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
  |     version, status, reason = self._read_status()
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 279, in _read_status
  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 705, in readinto
  |     return self._sock.recv_into(b)
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1274, in recv_into
  |     return self.read(nbytes, buffer)
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1130, in read
  |     return self._sslobj.read(len, buffer)
  | KeyboardInterrupt

Query error: bq.vertical.failed_rows[invalid_count]: 
SELECT * FROM lt.datalake_awe_reporting_form_submit 
 WHERE NOT vertical IS NULL AND NOT vertical IN ('AUTOMOBILE.LEASEBUYOUT','AUTOMOBILE.PURCHASE','AUTOMOBILE.REFINANCE','BUSINESSLOAN','HOMEEQUITY','INVESTMENT','MORTGAGE.PURCHASE','MORTGAGE.REFINANCE','PERSONAL','REVERSEMORTGAGE')

  | Stacktrace:
  | Traceback (most recent call last):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/execution/query/query.py", line 181, in store
  |     self.sample_ref = sampler.store_sample(sample_context)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/sampler/soda_cloud_sampler.py", line 10, in store_sample
  |     sample_rows = sample_context.sample.get_rows()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/soda/sampler/db_sample.py", line 13, in get_rows
  |     return self.cursor.fetchall()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
  |     return method(self, *args, **kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 383, in fetchall
  |     return list(self._query_data)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 208, in _items_iter
  |     for page in self._page_iter(increment=False):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 250, in _page_iter
  |     page = self._next_page()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 373, in _next_page
  |     response = self._get_next_page_response()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/table.py", line 1589, in _get_next_page_response
  |     return self.api_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 784, in _call_api
  |     return call()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
  |     return retry_target(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
  |     return target()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 482, in api_request
  |     response = self._make_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 341, in _make_request
  |     return self._do_request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 379, in _do_request
  |     return self.http.request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/google/auth/transport/requests.py", line 549, in request
  |     response = super(AuthorizedSession, self).request(
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
  |     resp = self.send(prep, **send_kwargs)
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/sessions.py", line 687, in send
  |     r.content
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/models.py", line 838, in content
  |     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/requests/models.py", line 760, in generate
  |     for chunk in self.raw.stream(chunk_size, decode_content=True):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/response.py", line 623, in stream
  |     for line in self.read_chunked(amt, decode_content=decode_content):
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/response.py", line 815, in read_chunked
  |     self._update_chunk_length()
  |   File "/Users/albin/dev/py/env/soda-core-3.0.10-2/lib/python3.10/site-packages/urllib3/response.py", line 745, in _update_chunk_length
  |     line = self._fp.fp.readline()
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 705, in readinto
  |     return self._sock.recv_into(b)
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1274, in recv_into
  |     return self.read(nbytes, buffer)
  |   File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1130, in read
  |     return self._sslobj.read(len, buffer)
  | KeyboardInterrupt

Sending results to Soda Cloud
Error while executing Soda Cloud command response code: 400
{
  "code": "invalid_request",
  "message": "Failed request validation of SodaCoreInsertScanResultsCommand on the following properties:\nlogs[13].message: must not be empty\nlogs[15].message: must not be empty\nlogs[19].message: must not be empty\nlogs[21].message: must not be empty"
}
Soda Cloud Trace: 7434011320232420250
(soda-core-3.0.10-2) $

```

**Comment by jmarien** [comment]
SODA-1232
