### ISSUE TITLE
unexpected keyword argument 'experimental_python_types'

### ISSUE THREAD

**Issue by RobbertDM** [sodadata/soda-core#1822]
Hey there,
For Trino, the trino python client introduced a breaking change:
https://github.com/trinodb/trino-python-client/blob/master/CHANGES.md?plain=1#L27-L34

I believe this results in soda breaking for trino.
I think this line can be removed: https://github.com/sodadata/soda-core/blob/main/soda/trino/soda/data_sources/trino_data_source.py#L88

Terminal output:
```
soda test-connection -c configuration.yml -d ov
[16:28:19] Soda Core 3.0.26
[16:28:19] Could not connect to data source "ov": Connection.__init__() got an unexpected keyword argument 'experimental_python_types'
  | Connection.__init__() got an unexpected keyword argument 'experimental_python_types'
[16:28:19] Could not connect to data source "ov": Connection.__init__() got an unexpected keyword argument 'experimental_python_types'
  | Connection.__init__() got an unexpected keyword argument 'experimental_python_types'
Unable to connect to 'ov'.
Traceback (most recent call last):
  File "/home/robbert/.local/bin/soda", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/robbert/.local/lib/python3.10/site-packages/soda/telemetry/soda_tracer.py", line 78, in wrapper
    raise e
  File "/home/robbert/.local/lib/python3.10/site-packages/soda/telemetry/soda_tracer.py", line 71, in wrapper
    result = fn(*original_args, **original_kwargs)
  File "/home/robbert/.local/lib/python3.10/site-packages/soda/cli/cli.py", line 559, in test_connection
    has_valid_connection = ds.has_valid_connection()
AttributeError: 'NoneType' object has no attribute 'has_valid_connection'
```

**Comment by RobbertDM** [comment]
Thank you @vijaykiran !
