### ISSUE TITLE
Soda unable to profile bigquery due to complex subquery

### ISSUE THREAD

**Issue by louisnow** [sodadata/soda-core#1861]
```
2023-04-24 05:26:24.011 ERROR log - log_to_python_logging: [05:26:24] Query error: events.profiling-partners-opportunity_acv_converted_rounded-value-frequencies-numeric: 400 Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or query is too complex.

Location: US
Job ID: eb74f7b5-62f4-441e-8ad1-71eb497b875b


WITH
    value_frequencies AS (
        SELECT `opportunity_acv_converted_rounded` AS value_, count(*) AS frequency_
        FROM certified_data.partners
        WHERE `opportunity_acv_converted_rounded` IS NOT NULL
        GROUP BY `opportunity_acv_converted_rounded`
    ),
    mins AS (
        SELECT CAST('mins' AS STRING) AS metric_, ROW_NUMBER() OVER(ORDER BY value_ ASC) AS index_, value_, frequency_
        FROM value_frequencies
        WHERE value_ IS NOT NULL
        ORDER BY value_ ASC
        LIMIT 5
    ),
    maxs AS (
        SELECT CAST('maxs' AS STRING) AS metric_, ROW_NUMBER() OVER(ORDER BY value_ DESC) AS index_, value_, frequency_
        FROM value_frequencies
        WHERE value_ IS NOT NULL
        ORDER BY value_ DESC
        LIMIT 5
    ),
    frequent_values AS (
        SELECT CAST('frequent_values' AS STRING) AS metric_, ROW_NUMBER() OVER(ORDER BY frequency_ DESC) AS index_, value_, frequency_
        FROM value_frequencies
        ORDER BY frequency_ desc
        LIMIT 10
    ),
    result AS (
        SELECT * FROM mins
        UNION ALL
        SELECT * FROM maxs
        UNION ALL
        SELECT * FROM frequent_values
    )
SELECT *
FROM result
ORDER BY metric_ ASC, index_ ASC

2023-04-24 05:26:24.012 ERROR log - log_to_python_logging:   | 400 Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or query is too complex.

2023-04-24 05:26:24.012 ERROR log - log_to_python_logging:   | Stacktrace:
2023-04-24 05:26:24.012 ERROR log - log_to_python_logging:   | Traceback (most recent call last):
  |   File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 203, in _execute
  |     self._query_job.result()
  |   File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
  |     do_get_result()
  |   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
  |     return retry_target(
  |   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target
  |     return target()
  |   File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
  |     super(QueryJob, self).result(retry=retry, timeout=timeout)
  |   File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
  |     return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  |   File "/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
  |     raise self._exception
  | google.api_core.exceptions.BadRequest: 400 Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or query is too complex.

```

**Comment by jmarien** [comment]
SODA-1719

**Comment by louisnow** [comment]
Thanks for the quick reply @jmarien. Really appreciate it. However we are still seeing the error.

`opportunity_tcv_converted_rounded` is a float datatype in case that helps

```
2023-04-25 05:51:48.644 ERROR log - log_to_python_logging: [05:51:48] Database returned no results for histograms in table: partners, columns: opportunity_acv_converted_rounded
2023-04-25 05:51:52.531 ERROR log - log_to_python_logging: [05:51:52] Query error: events.profiling-partners-opportunity_tcv_converted_rounded-value-frequencies-numeric: 400 Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or query is too complex.

Location: US
Job ID: 6c416af9-eb97-40b4-b632-36b0ed8e156e


WITH
    value_frequencies AS (
        SELECT `opportunity_tcv_converted_rounded` AS value_, count(*) AS frequency_
        FROM certified_data.partners
        WHERE `opportunity_tcv_converted_rounded` IS NOT NULL
        GROUP BY `opportunity_tcv_converted_rounded`
    ),
    mins AS (
        SELECT CAST('mins' AS STRING) AS metric_, ROW_NUMBER() OVER(ORDER BY value_ ASC) AS index_, value_, frequency_
        FROM value_frequencies
        WHERE value_ IS NOT NULL
        ORDER BY value_ ASC
        LIMIT 5
    ),
    maxs AS (
        SELECT CAST('maxs' AS STRING) AS metric_, ROW_NUMBER() OVER(ORDER BY value_ DESC) AS index_, value_, frequency_
        FROM value_frequencies
        WHERE value_ IS NOT NULL
        ORDER BY value_ DESC
        LIMIT 5
    ),
    frequent_values AS (
        SELECT CAST('frequent_values' AS STRING) AS metric_, ROW_NUMBER() OVER(ORDER BY frequency_ DESC) AS index_, value_, frequency_
        FROM value_frequencies
        ORDER BY frequency_ desc
        LIMIT 10
    ),
    results AS (
        SELECT * FROM mins
        UNION ALL
        SELECT * FROM maxs
        UNION ALL
        SELECT * FROM frequent_values
    )
SELECT *
FROM results
ORDER BY metric_ ASC, index_ ASC

2023-04-25 05:51:52.531 ERROR log - log_to_python_logging:   | 400 Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or query is too complex.
```

**Comment by benjamin-pirotte** [comment]
Hi, thank you for your ticket. We are looking into this issue. I will let you know as soon as I have update.

**Comment by benjamin-pirotte** [comment]
Hi Louis, 

I checked with the engineering team and it would require substantial research and rethinking of how we do profiling. So, unfortunately, we will not be able to fix it in the short term. However, I added it to our backlog. 

To understand the priority, how critical profiling is to you? And how much this issue is a blocker for you? Do you have that on multiple tables/data sources?

Could you also maybe let me know a bit more about how big is the table and what is in it? So we could potentially generate a similar table to try to reproduce the issue.

Thanks a lot for your understanding and feedback!
